# fly.toml app configuration file generated for phlo on 2023-05-14T23:07:28+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
# This is the exact config used to deploy this starter to fly.io
#

app = "phlo"
primary_region = "lhr"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
